"""Create a private `.env.local` without echoing API keys to the terminal."""

from __future__ import annotations

import getpass
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
ENV_LOCAL = REPO_ROOT / ".env.local"

API_ENV_VARS: tuple[tuple[str, str], ...] = (
    ("ALPHA_VANTAGE_API_KEY", "Alpha Vantage"),
    ("TIINGO_TOKEN", "Tiingo"),
    ("FMP_API_KEY", "Financial Modeling Prep"),
    ("POLYGON_API_KEY", "Polygon"),
    ("INTRINIO_API_KEY", "Intrinio"),
    ("FRED_API_KEY", "FRED"),
    ("BLS_API_KEY", "BLS"),
    ("CFTC_APP_TOKEN", "CFTC"),
    ("CONGRESS_GOV_API_KEY", "Congress.gov"),
    ("ECONDB_API_KEY", "EconDB"),
    ("EIA_API_KEY", "EIA"),
    ("NASDAQ_API_KEY", "Nasdaq Data Link"),
)


def quote_env_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def collect_credentials(env_vars: Iterable[tuple[str, str]]) -> dict[str, str]:
    credentials: dict[str, str] = {}
    for env_var, label in env_vars:
        value = getpass.getpass(f"{label} ({env_var}) - lascia vuoto per saltare: ").strip()
        if value:
            credentials[env_var] = value
    return credentials


def write_env_local(credentials: dict[str, str], path: Path = ENV_LOCAL) -> Path:
    lines = [
        "# Private local API credentials.",
        "# Generated by data/private_api_activation.py and ignored by git.",
        "OPENBB_USE_ENV_CREDENTIALS=1",
        "",
    ]
    lines.extend(f"{key}={quote_env_value(value)}" for key, value in sorted(credentials.items()))
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o600)
    return path


def main() -> None:
    print("Creo/aggiorno .env.local privato. Le chiavi non vengono mostrate a schermo.")
    credentials = collect_credentials(API_ENV_VARS)
    if not credentials:
        print("Nessuna credenziale inserita. .env.local non modificato.")
        return
    path = write_env_local(credentials)
    print(f"Creato {path} con {len(credentials)} credenziali. File ignorato da git.")


if __name__ == "__main__":
    main()
